image: registry.gitlab.com/baldissera/nexteimageserver
stages:
  - build
  - test

build:
  stage: build
  before_script:
    - cd app 
  script:
    - go build app.go

unit_test:
  stage: test
  before_script:
    - cd app 
  script:
    - go test -cover