image: registry.gitlab.com/baldissera/nexteimageserver
stages:
  - build
  # - test

build:
  stage: build
  before_script:
    - cd app 
  script:
    - go build app.go

# test:
#   stage: test
#   script:
#     - godep restore
#     - godep go test -v -cover ./...